spring:
  application:
    name: live-demo
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:bootapp;DB_CLOSE_DELAY=-1
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates
    suffix: .html
    encoding: UTF-8
management:
  endpoints:
    web:
      exposure:
        include: '*'
