spring:
  application:
    name: live-demo
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:bootapp;DB_CLOSE_DELAY=-1
    username: sa
    password:
management:
  endpoints:
    web:
      exposure:
        include: '*'
